### ISSUE TITLE
[BUG] No "pv.create" pillar data supplied - nothing to do!

### ISSUE THREAD

**Issue by BillyBombardieri** [saltstack-formulas/lvm-formula#21]
$ sudo salt 'pt-prod-billy' pillar.items lvm
```
pt-prod-billy:
    ----------
    lvm:
        ----------
        pv:
            ----------
            create:
                ----------
                /dev/xvdc:
                    ----------
                    options:
                        ----------
                        verbose:
                            True

```

$ sudo salt 'pt-prod-billy' state.apply lvm.pv.create
```
pt-prod-billy:
----------
          ID: lvm_pv_create_nothing_to_do
    Function: test.show_notification
      Result: True
     Comment: No "pv.create" pillar data supplied - nothing to do!
     Started: 13:26:21.435264
    Duration:  1.043 ms
```

I have "No "..." pillar data supplied - nothing to do!" for all state, just with lvm-formula
With other formula, it's works.

**Comment by noelmcloughlin** [comment]
Looks correct to me.  
You need to supply some data to `lvm.pv.create` ... see the examples:
https://github.com/saltstack-formulas/lvm-formula/blob/master/pillar.example#L38-L87
Instead of throwing an exception (dictionary is null) it prints `lvm_pv_create_nothing_to_do` state.

**Comment by BillyBombardieri** [comment]
I have this In my state : 
```
lvm:
  pv:
    create:
      /dev/xvdc: {}
  vg:
    create:
      data-vg:
        devices:
          - /dev/xvdc

```

**Comment by BillyBombardieri** [comment]
the first time I ran it, I got this message: 

 ```

      [...]
      ---
    - Rendering SLS 'base:lvm.pv.create' failed: Jinja error: lvm/map.jinja
      Traceback (most recent call last):
        File "/usr/local/lib/python3.8/dist-packages/salt/utils/templates.py", line 500, in render_jinja_tmpl
          output = template.render(**decoded_context)
        File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
          return original_render(self, *args, **kwargs)
        File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
          return self.environment.handle_exception(exc_info, True)
        File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
          reraise(exc_type, exc_value, tb)
        File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
          raise value.with_traceback(tb)
        File "<template>", line 3, in <module>
        File "/usr/local/lib/python3.8/dist-packages/salt/utils/jinja.py", line 198, in get_source
          raise TemplateNotFound(template)
      jinja2.exceptions.TemplateNotFound: lvm/map.jinja
      
      ; line 3
      
      ---
      # -*- coding: utf-8 -*-
      # vim: ft=sls
      {% from "lvm/map.jinja" import lvm with context %}    <======================
      {% from "lvm/templates/macros.jinja" import getopts with context %}
      
      {%- if lvm.pv and "create" in lvm.pv and lvm.pv.create is mapping %}
        {% for pv, pvdata in lvm.pv.create.items() if pv not in ('create', 'delete',) %}
      
      [...]
      ---

```

**Comment by BillyBombardieri** [comment]
it works with version 3001.8 of salt-ssh

**Comment by noelmcloughlin** [comment]
Could you edit `lvm/pv/create.sls`  or `lvm/vg/rename.sls` and change the text

from:  `No "xx.xxxx" pillar data supplied - nothing to to!`
to:  `No "xx.xxxx" pillar data supplied {{ lvm }} - nothing to do!`

i.e. what is value of ` lvm` jinja2 variable when these commands are executed.  It's type should be dict but seems to be None?

**Comment by sh1ny** [comment]
Getting the same. Here's what {{ lvm }} outputs:

```
----------
          ID: lvm_pv_create_nothing_to_do
    Function: test.show_notification
      Result: True
     Comment: No "pv.create" pillar data supplied {'pkgs': ['lvm2', 'cryptsetup', 'device-mapper-persistent-data'], 'cfgsource': 'salt://lvm/templates/conf.jinja', 'group': 'root', 'filemode': '0640', 'dir_mode': '0755', 'files': {'loopbackdir': '/tmp/loopdevs'}, 'kmodules': [], 'config': {'dir': {'profiles': '/etc/lvm/profile', 'backups': '/etc/lvm/backup'}}, 'profiles': {'default': {'thin-generic': {}, 'cache-mq': {}, 'command_profile_templater': {}, 'cache-smq': {}, 'lvmdbusd': {}}, 'remove': {}, 'create': {}, 'man5': {'manpage': 'lvm.conf(5)', 'vendor': 'kernel', 'format': {'div': '=', 'ucl': False, 'json': False}}}, 'vg': {'enable_export': False, 'enable_cfgrestore': False}, 'pv': {}, 'lv': {}, 'vgbase': ['lvroot']} - nothing to do!
     Started: 15:02:56.105095
    Duration: 1.38 ms
     Changes:
```

It's not only the pv.create, none of the lv,vg,pv work.

**Comment by sh1ny** [comment]
This seems to fix it. However this is a temp fix, i guess a proper one is in order ?

[root@sc-dev-lps-saltmaster001 lvm-formula]# git diff
diff --git a/lvm/map.jinja b/lvm/map.jinja
index c84acd2..02edb85 100644
--- a/lvm/map.jinja
+++ b/lvm/map.jinja
@@ -41,7 +41,8 @@
     )
 %}

-{%- set lvm = config %}
+# {%- set lvm = config %}
+{%- set lvm = salt['pillar.get']('lvm', default=defaults, merge=True) %}

 {#- Post-processing for specific non-YAML customisations #}
 {%- if grains.os == 'MacOS' %}
diff --git a/lvm/pv/create.sls b/lvm/pv/create.sls
index 0fe6977..b7fbfd9 100644
--- a/lvm/pv/create.sls
+++ b/lvm/pv/create.sls
@@ -18,6 +18,6 @@ lvm_pv_create_{{ pv }}:
 lvm_pv_create_nothing_to_do:
   test.show_notification:
     - text: |
-        No "pv.create" pillar data supplied - nothing to do!
+        No "pv.create" pillar data supplied {{ lvm }} - nothing to do!

 {%- endif %}
[root@sc-dev-lps-saltmaster001 lvm-formula]#

**Comment by noelmcloughlin** [comment]
Okay, something wrong with map.jinja I suppose.  Yes, please raise a PR to implement a fix.
